# Importing Libraries and Loading the Dataset

In [5]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [6]:
heart_df = pd.read_csv("heart.csv")
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 97.6 KB

In [7]:
heart_df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

# Data Preprocessing

In [8]:
#checking the null values
heart_df.isnull().sum().sum()

np.int64(0)

In [9]:
#checking the duplicate
heart_df.duplicated().sum()

np.int64(0)

In [10]:
#checking numeber of unique values in each features
heart_df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [11]:
#selecting categorical column
cat_col = heart_df.select_dtypes(include='object').columns
cat_col

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='str')

Converting Categorical values to Numerical

Sex: M-0 , F-1
ChestPainType: ATA-0, NAP-1, ASY-2, TA-3
RestingECG: Normal-0, ST-1, LVH-2
ExerciseAngina: N-0, Y-1
ST_Slope: Up-0, Flat-1, Down-2

In [12]:
for col in cat_col:
    print(col)
    print(heart_df[col].unique(), list(range(heart_df[col].nunique())))
    heart_df[col].replace((heart_df[col].unique()), range(heart_df[col].nunique()), inplace=True)
    print('*'*90)
    print()

Sex
<ArrowStringArray>
['M', 'F']
Length: 2, dtype: str [0, 1]
******************************************************************************************

ChestPainType
<ArrowStringArray>
['ATA', 'NAP', 'ASY', 'TA']
Length: 4, dtype: str [0, 1, 2, 3]
******************************************************************************************

RestingECG
<ArrowStringArray>
['Normal', 'ST', 'LVH']
Length: 3, dtype: str [0, 1, 2]
******************************************************************************************

ExerciseAngina
<ArrowStringArray>
['N', 'Y']
Length: 2, dtype: str [0, 1]
******************************************************************************************

ST_Slope
<ArrowStringArray>
['Up', 'Flat', 'Down']
Length: 3, dtype: str [0, 1, 2]
******************************************************************************************

In [13]:
for col in cat_col:
    print(col)
    
    # create mapping dictionary
    mapping = {val: idx for idx, val in enumerate(heart_df[col].unique())}
    print(mapping)
    
    # apply mapping
    heart_df[col] = heart_df[col].map(mapping)
    
    print('*' * 90)
    print()

Sex
{'M': 0, 'F': 1}
******************************************************************************************

ChestPainType
{'ATA': 0, 'NAP': 1, 'ASY': 2, 'TA': 3}
******************************************************************************************

RestingECG
{'Normal': 0, 'ST': 1, 'LVH': 2}
******************************************************************************************

ExerciseAngina
{'N': 0, 'Y': 1}
******************************************************************************************

ST_Slope
{'Up': 0, 'Flat': 1, 'Down': 2}
******************************************************************************************

In [14]:
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,0,140,289,0,0,172,0,0.0,0,0
1,49,1,1,160,180,0,0,156,0,1.0,1,1
2,37,0,0,130,283,0,1,98,0,0.0,0,0
3,48,1,2,138,214,0,0,108,1,1.5,1,1
4,54,0,1,150,195,0,0,122,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,3,110,264,0,0,132,0,1.2,1,1
914,68,0,2,144,193,1,0,141,0,3.4,1,1
915,57,0,2,130,131,0,0,115,1,1.2,1,1
916,57,1,0,130,236,0,2,174,0,0.0,1,1
917,38,0,1,138,175,0,0,173,0,0.0,0,0

Cholestrol cannot be zero, it states that the reading was not properlt noted

Imputing the zero values in cholestrol column with KNN Imputer

In [15]:
np.nan

nan

In [16]:
heart_df['Cholesterol'].replace(0,np.nan, inplace=True)

0      289.0
1      180.0
2      283.0
3      214.0
4      195.0
       ...
913    264.0
914    193.0
915    131.0
916    236.0
917    175.0
Name: Cholesterol, Length: 918, dtype: float64

In [17]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute, columns=heart_df.columns)

Doin same for Resting Blood Pressure

In [18]:
from sklearn.impute import KNNImputer
heart_df['RestingBP'].replace(0, np.nan, inplace=True)
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute, columns=heart_df.columns)

In [19]:
withoutOldPeak = heart_df.columns
withoutOldPeak = withoutOldPeak.drop('Oldpeak')
heart_df[withoutOldPeak] = heart_df[withoutOldPeak].astype('int32')

In [20]:
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int32
 1   Sex             918 non-null    int32
 2   ChestPainType   918 non-null    int32
 3   RestingBP       918 non-null    int32
 4   Cholesterol     918 non-null    int32
 5   FastingBS       918 non-null    int32
 6   RestingECG      918 non-null    int32
 7   MaxHR           918 non-null    int32
 8   ExerciseAngina  918 non-null    int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int32
 11  HeartDisease    918 non-null    int32
dtypes: float64(1), int32(11)
memory usage: 46.7 KB

Train Test Split

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    heart_df.drop('HeartDisease', axis=1),
    heart_df['HeartDisease'], 
    test_size=0.2,      # 20% test data
    random_state=42 ,    # for reproducibility
    stratify=heart_df['HeartDisease']
)

Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
best_solver = ''
test_score = np.zeros(6)
for i, n in enumerate(solver):
    lr=LogisticRegression(solver=n).fit(X_train, y_train)
    test_score[i] = lr.score(X_test, y_test)
    if lr.score(X_test, y_test) == test_score.max():
        best_solver = n

lr = LogisticRegression(solver=best_solver)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
print(f'LogisticRegression Score: {accuracy_score(y_test, lr_pred)}')

LogisticRegression Score: 0.8695652173913043

In [29]:
import pickle
file = open('LogisticRegression.pkl', 'wb')
pickle.dump(lr, file)

In [30]:
import os

print(os.path.getsize("LogisticRegression.pkl"))

972

In [25]:
print(lr.feature_names_in_)

['Age' 'Sex' 'ChestPainType' 'RestingBP' 'Cholesterol' 'FastingBS'
 'RestingECG' 'MaxHR' 'ExerciseAngina' 'Oldpeak' 'ST_Slope']

In [26]:
print(y_train.dtypes)

int32